### ISSUE TITLE
EDSR-LIIF baseline

### ISSUE THREAD

**Issue by fjt0324** [LeeHW-THU/A-LIIF#2]
Thanks for your excellent job， I noticed that the author of LIIF had made their pre-trained EDSR-LIIF model public but you didn't use it. The reason that you implement this baseline yourself is there exists some difference in the model architecture or just for fair comparison?

**Comment by LeeHW-THU** [comment]
hi @fjt0324 

Thank you for your interest in this work.

In my thesis, it is mentioned that the MLP part of the baseline used by LIIF is 256, and the reason why we use the MLP with 16 neurons as our comparison baseline is that we want a fair comparison. The experimental comparison clearly shows the difference between the shared MLP layer approach for LIIF and our adaptive approach (both use MLPs with 16 neurons). No remaining changes were made to the model architecture of LIIF, except that the number of neurons in the MLP layer was set to 16.

**Comment by fjt0324** [comment]
Got it, thank you!
